use_frameworks!

platform :ios, '8.0'

target 'mytestPod_Example' do
  pod 'mytestPod', :path => '../'

  target 'mytestPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
